name: base_flutter
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  dio: ^4.0.4
  tf_dio_cache: ^1.0.1
  equatable: ^2.0.5
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.6.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  google_maps_flutter: ^2.2.4
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  map_launcher: ^2.5.0+1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  flutter_phoenix: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_easyloading: ^3.0.5
  share: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_rounded_date_picker: ^2.0.2
  material_design_icons_flutter: ^5.0.6595
  flutter_html: ^2.2.1
  pin_code_fields: ^7.3.0
  image_picker: ^0.8.4+9
  flutter_svg: ^0.23.0+1





# can use it:
#  flutter_rating_bar: ^4.0.0



flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

